services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - "C:/Users/hp/Documents/Docker-HA/home_assistant:/config"
    environment: 
      TZ: Europe/Rome
    restart: always
    ports:
    - "8123:8123" 
    privileged: true

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - C:/Users/hp/Documents/Docker-HA/mosquitto/config:/mosquitto/config
    - C:/Users/hp/Documents/Docker-HA/mosquitto/log:/mosquitto/log
    - C:/Users/hp/Documents/Docker-HA/mosquitto/data:/mosquitto/data
    restart: always
    ports:
    - "1883:1883" 

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    volumes:
      - C:/Users/hp/Documents/Docker-HA/zigbee2mqtt/data:/app/data
    ports:
      # Frontend port
      - 8080:8080
    devices:
      - COM4:/dev/ttyUSB0
    depends_on:
      - mosquitto

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=hp
      - PGID=7999
      - TZ=Europe/Rome
      - CLI_ARGS= #optional
    volumes:
      - C:/Users/hp/Documents/Docker-HA/duplicati/config:/config
      - C:/Users/hp/Documents/Docker-HA/duplicati/backups:/backups
      - C:/Users/hp/Documents/Docker-HA:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Rome
      - SUBDOMAINS=hahbrm
      - TOKEN=00c6753b-a22c-458a-b351-f2ef670c77f4
      - LOG_FILE=false #optional
    volumes:
      - C:/Users/hp/Documents/Docker-HA/duckdns/config:/config #optional
    restart: unless-stopped

  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    volumes:
      - C:/Users/hp/Documents/Docker-HA/node-red:/data
    ports:
      - 1880:1880